 CREATE TABLE DEPARTMENT 
(
      DEPARTMENT_ID NUMERIC  NOT NULL,
      DEPARTMENT_NAME VARCHAR ,
      LOCATION_ID NUMERIC ,
      EMPLOYEE_EMPLOYEE_ID NUMERIC ,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY(DEPARTMENT_ID)
);
  CREATE TABLE EMPLOYEE 
(
      EMAIL VARCHAR ,
      EMPLOYEE_ID NUMERIC  NOT NULL,
      FIRST_NAME VARCHAR ,
      HIRE_DATE VARCHAR ,
      JOB_ID VARCHAR ,
      LAST_NAME VARCHAR ,
      PHONE_NUMBER VARCHAR ,
      SALARY NUMERIC ,
      DEPARTMENT_DEPARTMENT_ID NUMERIC ,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY(EMPLOYEE_ID)
);
 

CREATE TABLE DATA_SYNCH_ACTIONS 
(
      ID NUMERIC NOT NULL,
      SERVICE_CLASS_NAME VARCHAR NOT NULL,
      ENTITY_CLASS_NAME VARCHAR NOT NULL,
      JSON_PAYLOAD VARCHAR ,
      ACTION VARCHAR NOT NULL,
      DATE_CREATED DATE NOT NULL,
      DATE_LAST_SYNCH DATE NOT NULL,
      LAST_SYNCH_ERROR VARCHAR,
      CUSTOM_METHOD_NAME VARCHAR,
    CONSTRAINT DSA_PK PRIMARY KEY(SERVICE_CLASS_NAME ,ID)
);

CREATE TABLE WEB_SERVICE_CALL 
(
      ID NUMERIC  NOT NULL,
      CONNECTION VARCHAR ,
      REQUEST VARCHAR ,
      METHOD VARCHAR ,
      REQUEST_HEADERS VARCHAR ,
      DURATION NUMERIC ,
      REQUEST_PAYLOAD VARCHAR ,
      RESPONSE_PAYLOAD VARCHAR ,
      ERROR_MESSAGE VARCHAR ,
      TIMESTAMP DATE ,
    CONSTRAINT WEB_SERVICE_CALL_PK PRIMARY KEY(ID)
);
